### ISSUE TITLE
ngrok fails checksum

### ISSUE THREAD

**Issue by joallard** [caskroom/homebrew-cask#26140]
Tried to install `ngrok`:

```
$ brew cask install ngrok
==> Downloading https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-darwin-amd64.zip
######################################################################## 100.0%
==> Verifying checksum for Cask ngrok
==> Note: running "brew update" may fix sha256 checksum errors
Error: sha256 mismatch
Expected: 63c9aeee01956f2e9627581f78a2e498e3364455240d663ccf7184c86d0fe6e3
Actual: 379763f38394903d59c49842034e89861c641ce8449d97fa4317e1433b6c0a79
File: /Users/jon/Library/Caches/Homebrew/Cask/ngrok--2.1.14,4VmDzA7iaHb.zip
To retry an incomplete download, remove the file above.

 $ rm /Users/jon/Library/Caches/Homebrew/Cask/ngrok--2.1.14,4VmDzA7iaHb.zip

$ brew cask install ngrok
==> Downloading https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-darwin-amd64.zip
######################################################################## 100.0%
==> Verifying checksum for Cask ngrok
==> Note: running "brew update" may fix sha256 checksum errors
Error: sha256 mismatch
Expected: 63c9aeee01956f2e9627581f78a2e498e3364455240d663ccf7184c86d0fe6e3
Actual: 379763f38394903d59c49842034e89861c641ce8449d97fa4317e1433b6c0a79
File: /Users/jon/Library/Caches/Homebrew/Cask/ngrok--2.1.14,4VmDzA7iaHb.zip
To retry an incomplete download, remove the file above.
```

Anyone know why?

**Comment by adidalal** [comment]
We have a fairly comprehensive Reporting Bugs guide. If you follow it you'll see https://github.com/caskroom/homebrew-cask/blob/master/doc/reporting_bugs/a_cask_fails_to_install.md#sha256-mismatch-error, which links to the fix.

...fixed in https://github.com/caskroom/homebrew-cask/pull/26143, this time

**Comment by joallard** [comment]
Really sorry about that. If I can provide any insight in reading the issue template, I thought that guide was about the basics of reporting bugs (it says "instructions about reporting bugs"), so I insinctively skipped it. Maybe call it "check if it's one of the [frequent issues]" would help.

**Comment by vitorgalvao** [comment]
> it says "instructions about reporting bugs"

No, it says “our instructions for reporting bugs”. Notice the **our**.  It also says “[p]lease note that if it is apparent you ignored the instructions for reporting issues, your issue may be closed without review” and hammer on the point of how skipping the guide leads to maintainer burnout.

Even if they were on the basics of bug reporting, with all that hammering on one point I don’t see it as justifiable to simply skip the guide we ask you repeatedly to follow.

**Comment by joallard** [comment]
Not everything has to be a confrontation you know? I apologized, tried to give you my perception in the hopes the issue template can be improved so that **you guys** can field less of misfiled bug reports. (There's no benefit for me, I don't triage the bugs here.) Your response? That my account of reading the guide is wrong.

Sorry for trying to help, I won't do that again here.

**Comment by vitorgalvao** [comment]
@joallard Apologies for my tone. Rereading, it looks worse than I intended.

I still don’t agree with you, though I do appreciate your suggestion. Once more, apologies for the strong tone, it came out differently than expected.
